title: Ruobing Bai's Homepage
page-top-title: Ruobing Bai
top-section-bg-text: Lithography
home-subtitle: Ruobing Bai&ensp;|&ensp;白若冰
copyright-text: '&copy; Ruobing Bai 2025-2030. All Rights Reserved.'
